=== aortegatornel/Servicios_Software/src/main/resources/aseguradoraSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.unican.es/ss/SegudosDomain" 
	xmlns:tns="http://www.unican.es/ss/SegudosDomain" 
	elementFormDefault="qualified">
	
 	<xs:simpleType name="DNI">
		<xs:restriction base="xs:ID">
			<xs:pattern value="[A-Z][-][0-9]{3}[-][A-Z]{6}"/>
		</xs:restriction>
	</xs:simpleType>
	
	
 	<xs:complexType name="Cliente">
 		<!--para que un cliente tenga mas de un seguro y un parte se define minimo y maximo del elemento -->
 		<xs:sequence>
 			<xs:element name="seguros" type="tns:Seguro" minOccurs="0" maxOccurs="unbounded"/>	
 			<xs:element name="parte" type="tns:Parte" minOccurs="0" maxOccurs="unbounded"/>
 		</xs:sequence>
 		<xs:attribute name="nombre" type="xs:string" use="required"/>
 		<xs:attribute name="email" type="xs:string" use="required"/>
 		<xs:attribute name="dni" type="tns:DNI" use="required"/>
 	</xs:complexType>
 	
 	<xs:simpleType name="Matricula">
		<xs:restriction base="xs:ID">
			<xs:pattern value="[A-Z]{3}[0-9]{4}"/>
		</xs:restriction>
	</xs:simpleType>
 	
 	<xs:complexType name="Vehiculo">
 		<xs:attribute name="matricula" type="tns:Matricula" use="required"/>
 		<xs:attribute name="cv" type="xs:integer" use="required"/>
 		<xs:attribute name="esProfesional" type="xs:boolean" use="required"/>
 	</xs:complexType>
 	
 	<xs:simpleType name="Id">
 			<xs:restriction base="xs:ID">
 				<xs:pattern value="[A-Z][0-9]{4}"/>
 			</xs:restriction>
 	</xs:simpleType>
 			
	<xs:complexType name="Seguro">
 		<xs:sequence>
 			<xs:element name="vehiculo" type="tns:Vehiculo" minOccurs="0" maxOccurs="unbounded"/>
 		</xs:sequence>
 		<xs:attribute name="id" type="tns:Id" use="required"/>
 		<xs:attribute name="precioBase" type="xs:double" use="required"/>
 	</xs:complexType>	
 	
 	<xs:complexType name="Parte">
 		<xs:attribute name="importe" type="xs:double" use="required"/>
 		<xs:attribute name="fecha" type="xs:dateTime" use="required"/>
 		<!-- para hacer referencia a un ID unico se usa IDREF -->
 		<xs:attribute name="seguroRef" type="xs:IDREF" use="required"/>
		<xs:attribute name="idParte" type="xs:int" use="required"/>
 	</xs:complexType>
 	
 	<xs:complexType name="Terceros">
 		<xs:complexContent>
 			<xs:extension base="tns:Seguro"/>
 		</xs:complexContent>
	</xs:complexType>	
	
	<xs:complexType name="TodoRiesgo">
 		<xs:complexContent>
 			<xs:extension base="tns:Seguro"/>
 		</xs:complexContent>
	</xs:complexType>	
	
	<xs:complexType name="TRFranquicia">
 		<xs:complexContent>
 			<xs:extension base="tns:Seguro"/>
 		</xs:complexContent>
	</xs:complexType>
	
	<xs:element name="Aseguradora">
		<xs:complexType>
		 <xs:sequence>
		  <xs:element name="cliente" type="tns:Cliente" minOccurs="0" maxOccurs="unbounded"></xs:element>
		 </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== aortegatornel/Servicios_Software/src/main/resources/aseguradora.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Aseguradora xmlns:tns="http://www.unican.es/ss/SegudosDomain" 
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
				 xsi:schemaLocation="http://www.unican.es/ss/SegudosDomain AseguradoraSchema.xsd ">
				 
  <tns:cliente dni="S-123-AQHYGW" email="correoDeEjemplo@correo.com" nombre="Andrés Ortega">
    <tns:seguros id="A0001" precioBase="200.0">
      <tns:vehiculo matricula="PLL9597" cv="75" esProfesional="false"/>
    </tns:seguros>
  </tns:cliente>
  
  <tns:cliente nombre="Pablo Prieto" email="correoDeEjemplo2@correo.com" dni="A-173-AQXYGQ">
    <tns:seguros id="A0002" precioBase="600.0">
      <tns:vehiculo matricula="PLX9597" cv="105" esProfesional="true"/>
    </tns:seguros>

    <tns:seguros id="A0003" precioBase="200.0">
      <tns:vehiculo matricula="PLX9797" cv="60" esProfesional="false"/>
    </tns:seguros>
    
    <tns:parte importe="350.0" fecha="2001-12-31T12:00:00" seguroRef="A0002"
    	idParte="001" />
    	
    <tns:parte importe="350.0" fecha="2001-12-31T12:00:00" seguroRef="A0002"
    	idParte="002" />
    
  </tns:cliente>
  
  <tns:cliente nombre="Lucía Rodriguez" email="correoDeEjemplo3@correo.com" dni="P-183-AQHYGW" >
    <tns:seguros id="A0004" precioBase="600.0">
      <tns:vehiculo matricula="JLL9551" cv="150" esProfesional="true"/>
    </tns:seguros>
  </tns:cliente>
  
</tns:Aseguradora>
